services:
  backend:
    container_name: reels_backend
    image: rohitdarekar816/reelsfeed:latest
    ports:
      - 5004:5004
    env_file:
      - .env

  telegram:
    container_name: telegram_bot
    image: rohitdarekar816/urlsender:latest
    env_file:
      - ./telegram_bot/.env
      